### ISSUE TITLE
Headers seem to glitch when populating the template containing them

### ISSUE THREAD

**Issue by tmjvonboss** [unidoc/unioffice#229]
## Description
I'm trying to populate a template.docx with text, the template just contains a header and a footer
I know that this library doesn't automatically add headers and footers into the output file, even if it originated from an input file that had them
So I manually add them in

* Text blurred in the screenshots below is just because of copyright and the text itself isn't the issue anyways but the text posisition is
## Expected Behavior
![template](https://user-images.githubusercontent.com/19273183/49894086-55c96900-fe4d-11e8-8fc0-030e3d39c930.png)
The orange text should be above the line in the header

## Actual Behavior
![populated_template](https://user-images.githubusercontent.com/19273183/49894090-58c45980-fe4d-11e8-8ea7-57176c33cff7.png)
The orange text is below the line in the header

```
//Open file
doc, err := document.OpenTemplate("template.docx")
if err != nil {
	log.Fatalf("error opening Windows Word 2016 document: %s", err)
}
headers := doc.Headers()

//using a loop here will cause "cant load picture error", caused by using wml.ST_HdrFtrDefault for each header
doc.BodySection().SetHeader(headers[0], wml.ST_HdrFtrFirst)
doc.BodySection().SetHeader(headers[1], wml.ST_HdrFtrFirst)
doc.BodySection().SetHeader(headers[2], wml.ST_HdrFtrDefault)
footers := doc.Footers()

//Using a loop here will cause the footer text to occur twice somehow
doc.BodySection().SetFooter(footers[0], wml.ST_HdrFtrDefault)
doc.BodySection().SetFooter(footers[1], wml.ST_HdrFtrDefault)

//populate with random text - left out for simplicity

//writing file
err = doc.SaveToFile("new_populate_test.docx")
if err != nil{
	fmt.Println(err)
}
```

Is there a way I can just copy my header and footer as is in my template?

**Comment by gunnsth** [comment]
@tmjvonboss Can you provide a sample file so we can reproduce the issue?
