### ISSUE TITLE
cell.AddTable produces not readable document

### ISSUE THREAD

**Issue by mosesonline** [unidoc/unioffice#234]
## Description
When I add a table into a cell and open the document in word (Office 365) I get a message that the document is not readable. I can repair it and it looks good, but not out of the box.

## Expected Behavior

I can add a table into a cell without error when opening in Word. Maybe an working example with table in table.

## Actual Behavior

I cannot add a table into a cell without error when opening in Word.

```
doc := document.New()

cell := doc.AddTable().AddRow().AddCell()
cell.AddTable().AddRow().AddCell().AddParagraph().AddRun().AddText("test")

doc.SaveToFile("test.docx")
```

**Comment by tbaliance** [comment]
Validation doesn't detect all errors, but it does detect this one.  Add this:
```
	if err := doc.Validate(); err != nil {
		log.Fatalf("error during validation: %s", err)
	}
```
and you'll see:
```
2018/12/24 09:15:08 error during validation: table cell must contain a paragraph
```

In this case, the paragraph must come after the table. 
```
	cell := doc.AddTable().AddRow().AddCell()
	cell.AddTable().AddRow().AddCell().AddParagraph().AddRun().AddText("test")
	cell.AddParagraph()
```
