### ISSUE TITLE
InsertRowAfter seems to skip rows in Document

### ISSUE THREAD

**Issue by nmjmdr** [unidoc/unioffice#238]
## Description
When attempting to add Row after the second row in table of 3 rows, InsertAfterRow seems to be inserting row after the third row:
Code:
```
func main() {

	doc, err := document.Open("./document.docx")
	if err != nil {
		fmt.Println("Error: ", err)
		return
	}

	tables := []document.Table{}
	for _, t := range doc.Tables() {
		tables = append(tables, t)
	}
	addNewRow(&tables[0], &tables[0].Rows()[1])

	doc.SaveToFile("document1.docx")
}

func addNewRow(t *document.Table, afterRow *document.Row) {
	row := t.InsertRowAfter(*afterRow)
	for i := 0; i < 2; i++ {
		row.AddCell().AddParagraph().AddRun().AddText("Hello")
	}
}
```
## Expected Behavior
The new row should be inserted after the second row

## Actual Behavior
The row is inserted after the the third row

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

[document.docx](https://github.com/baliance/gooxml/files/2762489/document.docx)
[document1.docx](https://github.com/baliance/gooxml/files/2762490/document1.docx)

**Comment by zgordan-vv** [comment]
fixed with https://github.com/unidoc/unioffice/pull/419 , please test

**Comment by gunnsth** [comment]
This should be fixed, closing.
