### ISSUE TITLE
Error after edit spreadsheet that contains images

### ISSUE THREAD

**Issue by ArmandoZepeda** [unidoc/unioffice#243]
## Description
Error on output file when editing existing spreadsheet with an image.
## Expected Behavior
I need to add new rows to an existing excel report with an image logo on top.
## Actual Behavior
When the existing file is loaded an warning message is shown:
`skipping unsupported element on Workbook {http://schemas.openxmlformats.org/markup-compatibility/2006 AlternateContent}
`

At opening on excel editor, I get the error:
`Removed Part: /xl/drawings/drawing1.xml part. (Drawing shape)
`

The image on the sheet is not edited or moved.
I tried to open and save the file(without perform changes) and the error persists.

[inputFile.xlsx](https://github.com/baliance/gooxml/files/2916143/inputFile.xlsx)
[outputFile.xlsx](https://github.com/baliance/gooxml/files/2916144/outputFile.xlsx)

My main.go code:

```
package main

import (
	"github.com/unidoc/unioffice/spreadsheet"
)

func main() {
	ss, _ := spreadsheet.Open("inputFile.xlsx")
	ss.SaveToFile("outputFile.xlsx")
}
```

**Comment by gunnsth** [comment]
@ArmandoZepeda Please post a full self-contained example with the code that takes inputFile.xlsx and produces outputFile.xlsx so we can reproduce this.

**Comment by ArmandoZepeda** [comment]
Hi. I'm sorry to return too late. I edited my post to include the code so, now it can be reproduced.
