### ISSUE TITLE
how to password protect an xlsx

### ISSUE THREAD

**Issue by MassimoMessina** [unidoc/unioffice#245]
## Description
I'm not able to set a password to open a workbook. If we save a workbook, the function Save() is producing a zip file that is not in the format required for the protected xlsx. Anyhow, I tried to protect using the setPassword() but it doesn't make the trick.

## Actual Behavior

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

                Ss = spreadsheet.New()
		Sp:= Ss.Protection()
		Sp.SetPassword("testpsw")
		Wrapped = Ss.StyleSheet.AddCellStyle()
		Wrapped.SetWrapped(true)
		Wrapped.SetVerticalAlignment(sml.ST_VerticalAlignmentCenter)

		sheet := Ss.AddSheet()
		sheet.SetName(mgr.Name)
		sheet.Column(1).SetWidth(4 * measurement.Inch)
		sheet.Column(2).SetWidth(2 * measurement.Inch)
		sheet.Column(2).SetWidth(2 * measurement.Inch)
		sheet.Column(2).SetWidth(2 * measurement.Inch)

		// Write Headers
		row := sheet.AddRow()
		cellA := row.AddCell()
		cellA.SetStyle(Wrapped)
		cellA.SetString("Name")

		if err := Ss.Validate(); err != nil {
			log.Fatalf("error validating sheet: %s", err)
		}

		ofil := "testpsw.xlsx"
		Ss.SaveToFile(ofil)
		log.Printf("\nData saved into:%s\n", ofil)

**Comment by nkryuchkov** [comment]
After a bit of research I found out that the password protection right now works according to the ooxml specification, and, indeed, this does not change the file format itself. However with the current version you may prevent the sheets from being edited. To achieve this you should add the protection to each shit in this fashion:

```
sheet := Ss.AddSheet()
sp := sheet.Protection()
sp.SetPassword("1234")
sp.LockObject(true)
sp.LockSheet(true)
```

Full password protection is related to #276

**Comment by gunnsth** [comment]
@MassimoMessina Does that make sense?

**Comment by MassimoMessina** [comment]
Hi, yes, but this is not preventing to open the file, and the content can be read without password.
best
Max

**Comment by gunnsth** [comment]
That is not possible at the present.  It requires implementation of #276.
