### ISSUE TITLE
[QUESTION] How to change the chart's style?

### ISSUE THREAD

**Issue by zarte** [unidoc/unioffice#246]
now:
![未命名](https://user-images.githubusercontent.com/26562491/54112539-5f00ac80-4421-11e9-9f51-7ef9fe47694b.png)

this is i want
![未命名2](https://user-images.githubusercontent.com/26562491/54112562-6a53d800-4421-11e9-99d2-e0aa29c24fc8.png)

**Comment by gunnsth** [comment]
@zarte Can you please post a self-contained example?  Are these charts in an Excel file that you are trying to modify?

**Comment by gunnsth** [comment]
Closing as this is missing information to reproduce.
