### ISSUE TITLE
cell range with sheet name not supported

### ISSUE THREAD

**Issue by hulb** [unidoc/unioffice#247]
## Description
normal cell range like "A1:A6" is fine.But when it comes with the specific sheet like "Sheet1!A1:A6" or "Sheet1A1:Sheet1A6" will fail in grammar analyzation.
## Expected Behavior
When a expr like "Sheet1!A1:A6" or "Sheet1!A1:Sheet1!A6", it can be correctly analyzed.
## Actual Behavior
A parse error occurs

**Comment by gunnsth** [comment]
@hulb Range as used into input into which functions ?  Can you post a self-contained example that reproduces this?

**Comment by hulb** [comment]
I just test the latest code and the problem I issued before doesn't exist. You guys must fix it. I'll close this issue.
