### ISSUE TITLE
[QUESTION] How to copy or delete sheets?

### ISSUE THREAD

**Issue by the-goodies** [unidoc/unioffice#263]
Is there a way to copy or delete an existing sheet? If anyone knows how to do that, example would be very appreciated.

**Comment by nkryuchkov** [comment]
Hi @the-goodies , I added the removing functions and ready to publish a PR, but it is not clear for me how you expect the copying to work. Could you please describe its functionality?

**Comment by the-goodies** [comment]
Well i'm not sure about the exact API, but given an existing sheet's name and a new name: create a new sheet which is a duplicate of old sheet. I need to create a spreadsheet which has 4-5 sheets depending on the amount of weeks in a month and want to fill first weeks sheet, then duplicate that sheet to a second week and do some modifications specific to that week.
If i can delete a sheet, then initially i can start with 5 sheets, fill them each separately and delete the last one if necessary.
