### ISSUE TITLE
hyperlink text is not visible with run.Text()

### ISSUE THREAD

**Issue by Savolro** [unidoc/unioffice#268]
## Description
I am trying to read a .docx document with this package but contents of hyperlink are missing.

Contents in my document:
`this is some http://liynk.com to somewhere`

I am trying to simply read the document and print its contents to console:
``` 
for _, p := range paragraphs {
    var str string
    for _, r := range p.Runs() {
        str += r.Text()
    }
    log.Println(str)
}
```

## Expected Behavior
Expected:
`this is some http://liynk.com to somewhere`

## Actual Behavior
Output:
`this is some  to somewhere`

Is it possible to print whole 'visible' content to console?

**Comment by gunnsth** [comment]
@Savolro Please follow the issue format:
## Description

## Expected Behavior

## Actual Behavior


Please include a reproducible code snippet or document attachment that
demonstrates the issue.

Make sure to include full code snippet that we can run.

**Comment by gunnsth** [comment]
@Savolro Can you post a full self-contained example containing a docx file to and we can run just with `go run example.go` ?  Your question may depend on how the link is created, i.e. what kind of object it is represented with etc, thus it is important to have the docx file too.

**Comment by gunnsth** [comment]
@Savolro Can you send an example .docx file ?  Otherwise it is difficult to reproduce this.
