### ISSUE TITLE
gooxml Installation

### ISSUE THREAD

**Issue by Sathyavathi2018** [unidoc/unioffice#272]
## Description

   With Reference to #270. Is there a way to install package from github rather baliance.com which will avoid referred issue in future

Current Installation
go get baliance.com/gooxml/
go build -i baliance.com/gooxml/...

Kindly, check and confirm.

**Comment by gunnsth** [comment]
@Sathyavathi2018 As per our announcement on: https://github.com/baliance/gooxml
We will be moving the repository to https://github.com/unidoc/unioffice

Best,
Gus

**Comment by Sathyavathi2018** [comment]
@gunnsth : Thanks for the confirmation. Will wait till then.

**Comment by gunnsth** [comment]
The repository has been moved to https://github.com/unidoc/unioffice and import path to github.com/unidoc/unioffice and package name is now unioffice.
