### ISSUE TITLE
Unidoc/UniOffice Compilation Issue due to internal reference in vendor

### ISSUE THREAD

**Issue by Sathyavathi2018** [unidoc/unioffice#282]
## Description
With Reference to #272 . 
After the latest github package installation. We are receiving below error
Current Installation
go get  github.com/unidoc/unioffice/
go build -i  -i github.com/unidoc/unioffice/...

**Error Received:**
cannot use img (type "github.com/gellyn/gastrayda/server/vendor/github.com/unidoc/unioffice/common".Image) as type "baliance.com/gooxml/common".Image in argument

 cannot use "github.com/gellyn/gastrayda/server/vendor/github.com/unidoc/unioffice/schema/soo/wml".ST_TabJcCenter (type "github.com/gellyn/gastrayda/server/vendor

As per the above error,  vendor files are referring to baliance.com/gooxml rather  github.com/unidoc/unioffice/

Kindly, check and confirm.

**Comment by Sathyavathi2018** [comment]
Hi, Do we have any update on this?

**Comment by nkryuchkov** [comment]
Hi @Sathyavathi2018 . I followed the steps you hade provided and everything works fine to me. It seems like some old code in you project still references old import paths. Probably you should check it out

**Comment by Sathyavathi2018** [comment]
Hi ,

   It worked after importing parent package as referred  below:
        _ "github.com/unidoc/unioffice"
	"github.com/unidoc/unioffice/color"
	"github.com/unidoc/unioffice/common"
	"github.com/unidoc/unioffice/document"
	"github.com/unidoc/unioffice/measurement"

	"github.com/unidoc/unioffice/schema/soo/wml"

We are good after the above implementation.
