### ISSUE TITLE
Text extraction

### ISSUE THREAD

**Issue by backkem** [unidoc/unioffice#284]
## Description
We want to extract all text from office documents for further processing. We're already doing this with unidoc and would like to have the same capability in unioffice. Preferably avoiding the need for custom parsing of each document type. Maybe I missed something and this is already available? If not, would you conciser supporting this use-case?

## Expected Behavior
Preferably we have an interface like unidoc/pdf/extractor that we can use to extract all text from a document:
https://github.com/unidoc/unicli/blob/4356cda5e49f2488ba6be6398b3b4cb73a553a07/pdf/extract.go#L27

**Comment by nkryuchkov** [comment]
Hello @backkem ! Could you please take a look at the func suggested with the #300 ? This is a prototype for now, I think we could use your feedback to improve it

**Comment by 5andr0** [comment]
@nkryuchkov This doesn't cover TextBoxes. Is there a way to get/edit Text inside TextBoxes?

**Comment by zgordan-vv** [comment]
https://github.com/unidoc/unioffice/releases/tag/v1.8.0 contains text extraction with TextBox support
