### ISSUE TITLE
Go module download failed

### ISSUE THREAD

**Issue by maxnilz** [unidoc/unioffice#285]
## Description
```
$ go version
go version go1.12.1 linux/amd64

$ go get github.com/unidoc/unioffice
```
## Expected Behavior
download pkg successfully

## Actual Behavior

```
$ go get github.com/unidoc/unioffice
go: github.com/unidoc/unioffice@v1.0.1: parsing go.mod: unexpected module path "baliance.com/gooxml"
go: error loading module requirements
```

**Comment by gunnsth** [comment]
A new version has been tagged which should fix this issue.

**Comment by maxnilz** [comment]
Thanks for your quick reply.

After I got this error, I tried `go get github.com/unidoc/unioffice@none` first and `go get github.com/unidoc/unioffice` again, then I got a new version and the issue disappeared.
