### ISSUE TITLE
Ability to merge docx files

### ISSUE THREAD

**Issue by yungsem** [unidoc/unioffice#287]
Will it be possible for you to add docx merging api ?
I know this is a very difficult and heavy job, but I really look forward to seeing you add this funciton.
Hope for your reply. Thank you.

**Comment by gunnsth** [comment]
Needs some investigation into what docx merging requires.  Off the top of my head:
- An easy, quick way could be via subdocument embedding (#277) with a master file referencing the others.
- More proper way would require loading each file, and copying to the master file, keeping all ids unique.  Page overlap could happen between documents as docx does not have page concept. Perhaps could force each document to end with a forced page-break.

It would make sense to create examples for merging and if it makes sense, a higher level API could be created.

**Comment by bsbak** [comment]
Looking for this feature too! Have a presentation file docx and all other files docx and i want append presentation to begining of each file.

**Comment by gunnsth** [comment]
Support for this has been added, see example
https://github.com/unidoc/unioffice-examples/blob/master/document/merge-documents/main.go
