### ISSUE TITLE
Document Mail Merge: Can not find field in a text box also generated file is corrupted

### ISSUE THREAD

**Issue by FourShore** [unidoc/unioffice#290]
## Description
When doing a document mail merge an a file that has a text box the merge fields in the text box do not get injected. Also the resulting file is unopenable by word.

## Expected Behavior
Merge fields in the text box to be injected with the value

## Actual Behavior
See above

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

[issue.docx](https://github.com/unidoc/unioffice/files/3254348/issue.docx)

**Comment by gunnsth** [comment]
@FourShore  Can you please include the code snippet that you are using for the "mail merge" so we can reproduce the issue.

**Comment by FourShore** [comment]
func Inject(file []byte, data map[string]string) ([]byte, error) {
	d, err := document.Read(bytes.NewReader(file), int64(len(file)))
	if err != nil {
		return nil, err
	}

	d.MailMerge(data)

	b := &bytes.Buffer{}

	err = d.Save(b)
	if err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

**Comment by zgordan-vv** [comment]
@FourShore can you list steps how this document was created? The source itself looks invalid, all merge fields are in <AlternateContent> tags and without <FldChar> tags which are vital for merging.
