### ISSUE TITLE
can't access table in header in 1.1.0 version

### ISSUE THREAD

**Issue by zhangpy** [unidoc/unioffice#296]
## Description
![x](https://user-images.githubusercontent.com/52045/59251392-48eecc00-8c5c-11e9-9164-3b756f25abf3.png)

## Expected Behavior
doc.Tables() or Paragraphs() should access the table in header. 

## Actual Behavior
```
doc, _ := document.Open("abc.docx")
for _, h := range doc.Headers() {
	for _, p := range h.Paragraphs() {
		ttt := ""
		for _, r := range p.Runs() {
			ttt += r.Text()
		}
		println(ttt)
	}
}
only body's paragraph is printed out.
```

Please include a reproducible code snippet or document attachment that
demonstrates the issue.
[abc.docx](https://github.com/unidoc/unioffice/files/3275167/abc.docx)

**Comment by nkryuchkov** [comment]
Hello @zhangpy ! Please try out the version in #303 , it should work. Also added the corresponding tables handling to the `Footer`' version of `Paragraphs`
