### ISSUE TITLE
document: fails to handle table in text box

### ISSUE THREAD

**Issue by elonzh** [unidoc/unioffice#301]
## Description

using unioffice open the file then save it can reproduce this issue

[table_in_text_box.docx](https://github.com/unidoc/unioffice/files/3293807/table_in_text_box.docx)

## Expected Behavior

open the file as normal.

## Actual Behavior

The Word app says cannot open the file

lib version: github.com/unidoc/unioffice v1.2.0
word version:
![image](https://user-images.githubusercontent.com/8749411/59558729-5a085600-902b-11e9-9305-1c0002b0adf8.png)

**Comment by SEFI2** [comment]
Hi @elonzh! Yeah, there has been a bug before in v1.2.0, but you may try the new releases (the latest v1.7.1), which works well for your given situation.
