### ISSUE TITLE
[QUESTION] The "custom" properties in metadata

### ISSUE THREAD

**Issue by iris13579** [unidoc/unioffice#302]
Hello,
I hope to update the "custom" properties in the metadata of a .docx file. Is there any example?
![image](https://user-images.githubusercontent.com/49423902/59893106-58b1a180-940e-11e9-97d9-5118f671119d.png)

I noticed the exact case was considered in baliance.com\gooxml\schema\soo\ofc\docPropsVTypes\Vector.go.
But I've no idea how to use it in my code.
![image](https://user-images.githubusercontent.com/49423902/59893140-7d0d7e00-940e-11e9-844f-1d444c5526fe.png)

Thanks.

**Comment by gunnsth** [comment]
@iris13579 This has been implemented in PR #307.  Can you check and verify that it resolves your case?

**Comment by iris13579** [comment]
@gunnsth 
I have made changes locally to support custom metadata and it works on my code. But still very appreciate. Can I join the code-review activity?

And I have another request to insert one docx file into another one. More details of the request can be found at https://forum.golangbridge.org/t/how-to-insert-an-object-into-a-word-document-with-go/13794
Do you have plan to implement this feature? Thank you~

**Comment by gunnsth** [comment]
@iris13579 Sure, please join the code review.
Can you file an issue for embedding the docx file?

**Comment by iris13579** [comment]
Hi @gunnsth ,
https://github.com/unidoc/unioffice/issues/313 is created for embedding the docx file. 
Thank you!
