### ISSUE TITLE
Filling out the form fields: issue with paragraph containing several form fields

### ISSUE THREAD

**Issue by aibolorazbekov** [unidoc/unioffice#305]
## Description
I'm trying to fill out the form fields using `SetValue` method.  The document that i'm working with, contains several paragraphs. The paragraphs contains several form fields.
[https://i.ibb.co/RDzvSQG/25.png](url)
## Expected Behavior
I want to fill out all of the form fields in the document. And here is the code i'm running:
```
	doc, err := document.Open("form.docx")
	if err != nil {
		log.Fatalf("error opening form: %s", err)
	}

	for i := range doc.FormFields() {
		doc.FormFields()[i].SetValue("test")
	}

	doc.SaveToFile("filled-form.docx")
```
## Actual Behavior
However, not all of the form fields were filled out.
[https://i.ibb.co/6RqBNf9/26.png](url)

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by gunnsth** [comment]
@aibolorazbekov Can you check and confirm that PR #311 addresses this issue?
