### ISSUE TITLE
Templated slide numbers on presentation are not appearing on output

### ISSUE THREAD

**Issue by mec07** [unidoc/unioffice#310]
## Description
I have a template with slide numbers templated onto the master slides. I remove the slides and just use the templates. When I then output the presentation the slide numbers are no longer there.

## Expected Behavior
The templated slide numbers remain in the templates.

## Actual Behavior
The templated slide numbers are stripped out of the template.

Simplified version of what I'm doing (should reproduce the error):
```
	ppt, err := presentation.OpenTemplate("template.pptx")
	if err != nil {
		return err
	}

	for _, s := range ppt.Slides() {
		if err := ppt.RemoveSlide(s); err != nil {
			return err
		}
	}

	layout, err := ppt.GetLayoutByName("template 1")
	if err != nil {
		return err
	}

	slide, err := ppt.AddDefaultSlideWithLayout(layout)
	if err != nil {
		return err
	}

        if err := ppt.SaveToFile("output.pptx"); err != nil {
		return err
	}
```
Interestingly enough, if you just keep in the original slides and don't create any new slides, the original slides still have their slide numbers (although that's probably because their XML is not being modified, so maybe it's not that interesting an observation).

**Comment by mec07** [comment]
I've just created an example repo that demonstrates this problem: https://github.com/mec07/slide-numbers

**Comment by zgordan-vv** [comment]
@mec07 for keeping page numbers there is another method called AddSlideWithLayout. The description of AddDefaultSlideWithLayout says:

```
// AddDefaultSlideWithLayout tries to replicate what PowerPoint does when
// inserting a slide with a new style by clearing placeholder content and removing
// some placeholders.  Use AddSlideWithLayout if you need more control.
```

so if you will use AddSlideWithLayout instead of AddDefaultSlideWithLayout here https://github.com/mec07/slide-numbers/blob/master/main.go#L32 and here https://github.com/mec07/slide-numbers/blob/master/main.go#L37 , page numbers will not be removed.

**Comment by mec07** [comment]
Thanks!

**Comment by zgordan-vv** [comment]
@gunnsth Can be closed I think?
