### ISSUE TITLE
can not open the word demo file

### ISSUE THREAD

**Issue by Songjiadong** [unidoc/unioffice#315]
## Description
I am used to your demo unidoc\unioffice\_examples\document\use-template\main.go,and run successly about your demo,but don't open the file（use-template.docx） which is created by demo. my system environment includes （office 2016， win10）
![图片](https://user-images.githubusercontent.com/46697885/62610802-f4538e80-b936-11e9-8fc4-895cdeaedfaf.png)

## Actual Behavior

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by zhexiao** [comment]
I have the same problem. Using the demo code to generator Simple Text Formatting (simple.docx) successfully。 But my system cannot open that file. (win10, office 2016)

**Comment by zhexiao** [comment]
[simple.docx](https://github.com/unidoc/unioffice/files/3656745/simple.docx)

**Comment by gunnsth** [comment]
This has been addressed in PR #330 and merged into master. Would appreciate if you can confirm that this fixes the issue.

**Comment by zhexiao** [comment]
> This has been addressed in PR #330 and merged into master. Would appreciate if you can confirm that this fixes the issue.

Thanks, will try it again. Let you know when it's ok.
