### ISSUE TITLE
[spreadsheet] Cell.SetFormulaArray don't work

### ISSUE THREAD

**Issue by stdatiks** [unidoc/unioffice#318]
## Description
Cell.SetFormulaArray method not apply array function type.

||A|B|C|
|---|---|---|---|
|1|test A|10||
|2|test B|20||
|3|test A|30||
|4|test B|40||
|5||||
|6|result test A|?||
|7|result test B|?||
|8||||

``` go
// ...
sheet.Row(6).Cell("B").SetFormulaArray("MIN(IF(A1:A4=A6,B1:B4))")
sheet.Row(7).Cell("B").SetFormulaArray("MAX(IF(A1:A4=A7,B1:B4))")
// ...
```

## Expected Behavior
||A|B|C|
|---|---|---|---|
|1|test A|10||
|2|test B|20||
|3|test A|30||
|4|test B|40||
|5||||
|6|result test A|10||
|7|result test B|40||
|8||||

## Actual Behavior
||A|B|C|
|---|---|---|---|
|1|test A|10||
|2|test B|20||
|3|test A|30||
|4|test B|40||
|5||||
|6|result test A|#VALUE!||
|7|result test B|#VALUE!||
|8||||

**Comment by gunnsth** [comment]
@zgordan-vv Can you check if the recent work on functions addresses this?

**Comment by zgordan-vv** [comment]
> @zgordan-vv Can you check if the recent work on functions addresses this?

No, these functions were already applied before the recent work.

The other thing is that "MIN(IF(A1:A4=A6,B1:B4))" which is noticed here doesn't work in Excel and LibreOffice as well (with the data given in the post and with another one), showing #VALUE!

**Comment by stdatiks** [comment]
> The other thing is that "MIN(IF(A1:A4=A6,B1:B4))" which is noticed here doesn't work in Excel and LibreOffice as well (with the data given in the post and with another one), showing #VALUE!

Because these are [array formulas](https://www.vertex42.com/blog/excel-formulas/array-formula-examples.html)?

**Comment by gunnsth** [comment]
@zgordan-vv Is this fixed now?

**Comment by zgordan-vv** [comment]
> @zgordan-vv Is this fixed now?

yes
