### ISSUE TITLE
[document] Unlicensed version of UniOffice

### ISSUE THREAD

**Issue by 5k3105** [unidoc/unioffice#319]
## Description
'go build' any project in _examples\document folder returns:
``` 
Unlicensed version of UniOffice
- Get a license on https://unidoc.io
```
spreadsheet examples work fine and do not return the licence warning.
## Expected Behavior
open docx correctly.
## Actual Behavior
produced document says 'unreadable content'.

**Comment by tafarifilho** [comment]
+1

**Comment by sify21** [comment]
Also the .docx files in _examples\document contain the same warning.
