### ISSUE TITLE
Problem with Excel spreadsheet calculations

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unioffice#324]
## Description

A bug report was received via email.
> Anyway ... I have attached the XLSX that I am battling with. It is a small subset of an overall scheme. I have removed all the indirects/offsets.
> The workbook uses the functions EDATE, MID, MATCH/VLOOKUP I quickly coded/modified or copied from other githubs.
>
> Problems with strings in IF function eg if(A1=1,"a","b") numbers seem to work if(A1=1,0,1))
>
> It would be great indirects and offsets worked too.

## Expected Behavior
The workbook would calculate values and display correctly.

## Actual Behavior
Some functions not working.  Problem in formula parser.

A private excel workbook was attached for debugging.

**Comment by gunnsth** [comment]
@zgordan-vv Can you check if the file now works?

**Comment by zgordan-vv** [comment]
it works, yes
