### ISSUE TITLE
which API can make title centered(horizontal align center;)

### ISSUE THREAD

**Issue by fish2016** [unidoc/unioffice#331]
## Description
which API can make title centered????

![image](https://user-images.githubusercontent.com/18462875/65953318-4831ae00-e476-11e9-96cd-50055abcfcd7.png)

**Comment by fish2016** [comment]
I can find the function “SetVerticalAlignment(v sharedTypes.ST_VerticalAlignRun) ”， but can NOT find the function about Horizontal aligment

**Comment by fish2016** [comment]
I have found the solution
For example for centering etc see:
https://github.com/baliance/gooxml/blob/32d0f798930b92a15044b3a566a889a3eac3ca88/_examples/document/tables/main.go#L93

**Comment by chenxi2015** [comment]
doc := document.New()

	// 添加title
	para := doc.AddParagraph()
	run := para.AddRun()

	// make title centered
	para.Properties().SetAlignment(wml.ST_JcCenter)
	para.SetStyle("Title")
	run.AddText("建筑消防设施维护保养报告书")
