### ISSUE TITLE
ImageRef do not have relId

### ISSUE THREAD

**Issue by zhexiao** [unidoc/unioffice#332]
## Description
1. read image data 

 ```
 case unioffice.ImageType, unioffice.ImageTypeStrict:
		var iref common.ImageRef
		for i, f := range files {
			if f == nil {
				continue
			}
			if f.Name == target {
				path, err := zippkg.ExtractToDiskTmp(f, d.TmpPath)
				if err != nil {
					return err
				}
				img, err := common.ImageFromFile(path)
				if err != nil {
					return err
				}
				iref = common.MakeImageRef(img, &d.DocBase, d.docRels)
				d.Images = append(d.Images, iref)
				fmt.Println(d.Images[0].RelID())
				files[i] = nil
			}
		}
```

2. call func

```
      func MakeImageRef(img Image, d *DocBase, rels Relationships) ImageRef {
	    return ImageRef{img: img, d: d, rels: rels}
       }
```

3. struct

```
      type ImageRef struct {
	     d     *DocBase
	    rels  Relationships
	    img   Image
	    relID string
    }
```
## Expected Behavior
Image have relID.
## Actual Behavior
Image do not have relID.

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by zgordan-vv** [comment]
@zhexiao Actually relID does not make sense for image reference right after creating. As relID is the id of a relationship, it depends on how many relationships already exist on the document / header / footer to which this image reference will be added. Say, if the image reference is added to a header which already has one relationship, the reference will be `rId2`, if it has 2 relationships, the new one will be `rId3` etc. But we don't know in advance where the image reference will be used when creating it, so we create it with empty relID and then when the relID is known we use `SetRelID` method on the image reference to set it. For example:

```
func (d *Document) AddImage(i common.Image) (common.ImageRef, error) {
    r := common.MakeImageRef(i, &d.DocBase, d.docRels) // at this time relationship is not created so we don't know its id

    ...

    d.Images = append(d.Images, r)
    fn := fmt.Sprintf("media/image%d.%s", len(d.Images), i.Format)
    rel := d.docRels.AddRelationship(fn, unioffice.ImageType) // now relationship is created and we can pull id out of it
    r.SetRelID(rel.X().IdAttr) // we set RelID on the image reference

    ...

```
