### ISSUE TITLE
[document] setWidthPercent has no effect on cells

### ISSUE THREAD

**Issue by sify21** [unidoc/unioffice#333]
## Description
I'm reading the document table examples ( unioffice/_examples/document/tables/main.go ). The fifth table is not working as I expected. The code is:
```
// Fifth Table
	{
		table := doc.AddTable()
		table.Properties().SetWidthPercent(90)
		table.Properties().SetAlignment(wml.ST_JcTableCenter)
		borders := table.Properties().Borders()
		borders.SetAll(wml.ST_BorderSingle, color.Auto, 1*measurement.Point)

		row := table.AddRow()

		cell := row.AddCell()
		cell.Properties().SetWidthPercent(25)
		para := cell.AddParagraph()
		run := para.AddRun()
		run.AddText("hello")

		cell = row.AddCell()
		cell.Properties().SetWidthPercent(75)
		para = cell.AddParagraph()
		run = para.AddRun()
		run.AddText("world")
                ...
```
## Expected Behavior
The 'hello' cell should take up 1/4 of total width, and 'world' cell takes up 3/4.
## Actual Behavior
'hello' and 'world' cell each takes up half of the total width.

The document is in the repository:  unioffice/_examples/document/tables/tables.docx

**Comment by zgordan-vv** [comment]
All works as expected at least in MS Word for Mac version 16.37 , xml also looks good.
