### ISSUE TITLE
Excel formula functions: Batch 1

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unioffice#337]
## Description
Based on #336 the task is to implement and create testcases for the following functions:

- [x] CELL
- [x] CHOOSE
- [x] COLUMN
- [x] COLUMNS
- [x] COUNTIF
- [x] COUNTIFS
- [x] CLEAN

- [x] VALUE
- [x] ROW
- [x] ROWS

- [x] VLOOKUP (?)
- [x] LOOKUP
- [x] INDEX
- [x] MATCH
- [x] MAXA
- [x] MAXIFS
- [x] MINA
- [x] MINIFS
- [x] LARGE
- [x] LOWER
- [x] SMALL

- [x] IFS

- [x] OFFSET

- [x] ISBLANK
- [x] ISNONTEXT
- [x] ISNUMBER
- [x] ISTEXT
- [x] ISODD
- [x] ISERR
- [x] ISERROR
- [x] ISEVEN
- [x] ISFORMULA
- [x] ISLEAPYEAR
- [x] ISLOGICAL
- [x] ISNA
- [x] ISREF

- [x] FIND
- [x] FINDB
- [x] SEARCH
- [x] SEARCHB

- [x] SUMIF
- [x] SUMIFS
- [x] CONCAT
- [x] CONCATENATE
- [x] REPLACE
- [x] TEXT
- [x] TEXTJOIN

- [x] YEAR
- [x] YEARFRAC

- [x] NOW
- [x] TODAY
- [x] TIME
- [x] TIMEVALUE

- [x] DATETIME
- [x] DATE
- [x] DATEDIF
- [x] DATEVALUE
- [x] DAY
- [x] DAYS

- [x] MDURATION
- [x] MONTH
- [x] MINUTE

- [x] EDATE
- [x] EOMONTH

- [x] PDURATION

## Expected Behavior
Expect the functions to work on Excel spreadsheets and testcases to work.

## Actual Behavior
N/A

**Comment by zgordan-vv** [comment]
Some functions from list are discovered as already working (I just couldn't make them work when tested):

CLEAN
VLOOKUP

Will add more if discover

**Comment by zgordan-vv** [comment]
DAYSINMONTH, YEARS, ISEVEN_ADD, ISODD_ADD, MONTHS are only Open/Libre functions, so I suppose we can remove them from the list

**Comment by zgordan-vv** [comment]
DATEVALUE is already done and merged into master, MDURATION and PDURATION are done in https://github.com/unidoc/unioffice/pull/353

**Comment by gunnsth** [comment]
Updated.
