### ISSUE TITLE
添加全局样式的样式的时候发现。貌似document.ParagraphStyleProperties 没有Spacing方法设置行距

### ISSUE THREAD

**Issue by liangsssttt** [unidoc/unioffice#338]
## Description
描述如标题
## Expected Behavior
希望添加全局样式的时候对于段落样式的设置可以设置：行间距
## Actual Behavior
无法设置行间距。只能设置段前和段后间距

后来直接在源码中document.ParagraphStyleProperties

添加方法：
func (p ParagraphStyleProperties) Spacing() ParagraphSpacing {
	if p.x.Spacing == nil {
		p.x.Spacing = wml.NewCT_Spacing()
	}
	return ParagraphSpacing{p.x.Spacing}
}

即可解决问题。。-。-

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by gunnsth** [comment]
English please.
