### ISSUE TITLE
Reading from .pptx files

### ISSUE THREAD

**Issue by stephenfriedman** [unidoc/unioffice#343]
## Description
This is really just a question. Can the `unioffice/presentation` package be used to read text from a .pptx file? I have walked through the example where one can write to a file. I want to be able to extract text from .pptx files. I was hoping that my code as follows would be a way to get some text off a slide. But this method does not seem to return any text. Is trying to use this library for presentation text extraction a fruitless effort?

	p, err := presentation.Open("./static/my.pptx")
	if err != nil {
		t.Error(err)
	}
	someText := p.Slides()[0].PlaceHolders()[0].Paragraphs()[0].X().EG_TextRun[0].Fld.T
        // or this instead
	//someText := p.Slides()[0].PlaceHolders()[0].Paragraphs()[0].X().EG_TextRun[0].R.T

**Comment by gunnsth** [comment]
Yes, we can extract text from pptx, please see
https://github.com/unidoc/unioffice-examples/tree/master/presentation/text_extraction
example
and api documentation
https://apidocs.unidoc.io/unioffice/v1.10.0/github.com/unidoc/unioffice/presentation/#Presentation.ExtractText
