### ISSUE TITLE
a problem about function Cells() of spreadsheet which is wrong  when I Get length value 

### ISSUE THREAD

**Issue by Songjiadong** [unidoc/unioffice#347]
## Description
a problem about function Cells() of spreadsheet which is wrong  when I Get length value

	ss, _ := spreadsheet.Open("expert.xlsx")
	sheets := ss.Sheets()
	for _, item := range sheets[0].Rows() {
             cells:=item.Cells()
               log.Println(len(cells))
		for _,cellItem:=range cells{
			log.Println(cellItem)
		}
	}
![图片](https://user-images.githubusercontent.com/46697885/68364359-ad10b000-0168-11ea-9cf4-cc6e6442764a.png)

## Expected Behavior
length of cells is 6、6

## Actual Behavior
length of cells is 6、5 because of the second space of Row[3][4] which is ignore. but I can used Cell("E") function which is right.

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by gunnsth** [comment]
@zgordan-vv Can you check if our updated functions cover this ?

**Comment by zgordan-vv** [comment]
The issue is not related to formulas, I will look closer for exact reason.

**Comment by gunnsth** [comment]
@zgordan-vv Is this done?

**Comment by zgordan-vv** [comment]
> @zgordan-vv Is this done?

yes, in #351
