### ISSUE TITLE
Images disappear from presentation

### ISSUE THREAD

**Issue by probonopd** [unidoc/unioffice#349]
## Description

When working on a presentation using a template, it gets corrupted. As a result, when opening in PowerPoint, PowerPoint will "repair" the file but the references to images are lost. According to the pptx file size, the pictures are still in the file, but they don't show up in the presentation anymore.

## Expected Behavior

Pictures stay where they are when working with templates.

## Actual Behavior

According to the pptx file size, the pictures are still in the file, but they don't show up in the presentation anymore. Instead, warning signs are shown.

The following errors are shown:

```
2019/11/13 22:50:55 unsupported relationship type: http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesMaster tgt: ppt/notesMasters/notesMaster1.xml
2019/11/13 22:50:55 unsupported relationship type: http://schemas.openxmlformats.org/officeDocument/2006/relationships/handoutMaster tgt: ppt/handoutMasters/handoutMaster1.xml
2019/11/13 22:50:55 unsupported relationship type: http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps tgt: ppt/presProps.xml
2019/11/13 22:50:55 unsupported relationship type: http://schemas.openxmlformats.org/officeDocument/2006/relationships/viewProps tgt: ppt/viewProps.xml
2019/11/13 22:50:55 unsupported relationship type: http://schemas.openxmlformats.org/officeDocument/2006/relationships/tableStyles tgt: ppt/tableStyles.xml
```

If this bug is not known so far, please let me know and I will try to produce a pptx test file for it.

**Comment by gunnsth** [comment]
@probonopd Can you post a full self-contained example that can be used to reproduce the issue?

**Comment by mkhan-kilabs** [comment]
I have the same issue. I tried with the ppt template example - https://github.com/unidoc/unioffice/tree/master/_examples/presentation/use-template
and the image disappeared from the mod.pptx

**Comment by probonopd** [comment]
Yes, it also happens in the official example in `_examples/presentation/use-template/`.

Original `template.pptx` template on top, modified `mod.pptx` after running the `use-template` command below.

![bug](https://user-images.githubusercontent.com/2480569/69170667-64ef7700-0af2-11ea-9a53-8baacb257c45.png)

The Screenshots are made using SoftMaker Office but the same effect can be observed using PowerPoint.

Seems to happen with JPG but **not** with PNG.

In fact, this is the minimal code to reproduce it:

```
package main

import (
	"github.com/unidoc/unioffice/presentation"
)

func main() {
	ppt, _ := presentation.OpenTemplate("template.pptx")
	ppt.SaveToFile("mod.pptx")
}
```

Is this the culprit?

```diff
diff -r /home/me/go/src/demo/template.pptx/ppt/theme/_rels/theme1.xml.rels /home/me/go/src/demo/mod.pptx/ppt/theme/_rels/theme1.xml.rels
1,2c1,2
< <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
< <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/image1.jpeg"/></Relationships>
\ No newline at end of file
---
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships" xmlns:xml="http://www.w3.org/XML/1998/namespace"><Relationship Target="../media/image1.png" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId1"/></Relationships>

````

It rewrites `.jpeg` to `.png` in the XML, whereas the file is called `.jpeg`.

Possibly it is due to this line?

https://github.com/unidoc/unioffice/blob/26d9caa6f801ddf86869920bef9638d5ea1ff4d3/filenames.go#L157

Perhaps this does not work properly?

https://github.com/unidoc/unioffice/blob/26d9caa6f801ddf86869920bef9638d5ea1ff4d3/filenames.go#L204

**Comment by zgordan-vv** [comment]
@probonopd @mkhan-kilabs Can you test it with https://github.com/unidoc/unioffice/pull/395 ? Looks like it is fixed while working with another issue.

**Comment by zgordan-vv** [comment]
Can we close it? Test case works on master now.

**Comment by probonopd** [comment]
Thank you very much @zgordan-vv. Sorry I can't test it right now, so closing for now. Will reopen if the issue persists.
