### ISSUE TITLE
Excel functions: 10 most popular functions

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unioffice#355]
## Description
Based on #336 the task is to implement and create testcases for the following functions that are classified as the 10 most popular functions.
- [ ] SUM
- [ ] IF
- [x] LOOKUP
- [x] VLOOKUP
- [x] MATCH
- [x] CHOOSE
- [x] DATE
- [x] DAYS
- [x] FIND
- [x] FINDB
- [x] INDEX

## Expected Behavior
Expect to have implementation and test cases for each of those functions.

## Actual Behavior
I think we already have most of these implemented. The task is to go over and ensure we have proper implementation and testcases for each.

Please comment below if the functions are already implemented properly and I will update the checklist.

**Comment by zgordan-vv** [comment]
All of these are implemented, but SUM and IF have no test cases, will add them on Monday
