### ISSUE TITLE
Excel functions: financial functions

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unioffice#356]
## Description
Based on #336 the task is to implement and create testcases for the following functions that are classified as financial functions.

- [ ] ACCRINT
- [x] ACCRINTM
- [x] AMORDEGRC
- [x] AMORLINC
- [x] COUPDAYBS
- [x] COUPDAYS
- [x] COUPDAYSNC
- [x] COUPNCD
- [x] COUPNUM
- [x] COUPPCD
- [x] CUMIPMT
- [x] CUMPRINC
- [x] DB
- [x] DDB
- [x] DISC
- [x] DOLLARDE
- [x] DOLLARFR
- [x] DURATION
- [x] EFFECT
- [x] FV
- [x] FVSCHEDULE
- [x] INTRATE
- [x] IPMT
- [x] IRR
- [x] ISPMT
- [x] MDURATION
- [x] MIRR
- [x] NOMINAL
- [x] NPER
- [x] NPV
- [ ] ODDFRPRICE
- [ ] ODDFYIELD
- [x] ODDLPRICE
- [x] ODDLYIELD
- [x] PDURATION
- [x] PMT
- [x] PPMT
- [x] PRICE
- [x] PRICEDISC
- [x] PRICEMAT
- [x] PV
- [x] RATE
- [x] RECEIVED
- [x] RRI
- [x] SLN
- [x] SYD
- [x] TBILLEQ
- [x] TBILLPRICE
- [x] TBILLYIELD
- [x] VDB
- [x] XIRR
- [x] XNPV
- [x] YIELD
- [x] YIELDDISC
- [x] YIELDMAT

## Expected Behavior
Expect to have implementation and test cases for each of those functions.

## Actual Behavior
Some of these may be already implemented. The task is to go over and ensure we have proper implementation and testcases for each.

Please comment below if the functions are already implemented properly and I will update the checklist.

**Comment by zgordan-vv** [comment]
DURATION, MDURATION and PDURATION are implemented already
