### ISSUE TITLE
[Question] Append Word document

### ISSUE THREAD

**Issue by l0nax** [unidoc/unioffice#364]
## Description

Is it currently possible if we have two Word Documents (eg. _A_ and _B_) that we simply append document _A_ behind document _B_?

I havn't found a actual function that can do this.
So are there any possiblities to manually implement this or exists this feature already?

**Comment by gunnsth** [comment]
See related https://github.com/unidoc/unioffice/issues/287

@l0nax Can you comment on the use case, why you want to do this?  Do you want the 2nd document to continue straight after the first one or end the last page of the 1st one with a page break?

What about any common properties of the two documents, should they be ignored or should one be dominant or attempt to merge any properties as long as there are no conflicts?  Any comments suggestions are welcome to help understand this use case better.

**Comment by l0nax** [comment]
Yes, this Issue is a duplicate of #287.

Thanks @gunnsth for your support :D
