### ISSUE TITLE
[question] Delete column

### ISSUE THREAD

**Issue by polderudo** [unidoc/unioffice#367]
Is there any way to delete a column from a sheet?

**Comment by polderudo** [comment]
We have a valid license ... I will fill out a contact request

**Comment by gunnsth** [comment]
@polderudo Thanks, we have received your question.  We will look into it and answer you soon.

**Comment by gunnsth** [comment]
@polderudo We have implemented the basic functionality.  We also made it such that it updates basic references.  However, we are wondering how complex it should be regarding updating formulas that use ranges and such.
Can you comment a bit about the use case?  Why do you need to remove a column?
Do you need to update references and formulas that will move as a result?

**Comment by polderudo** [comment]
We are creating Excel files from our data as an export. We have different "settings" for exporting the data. Thus we want to create one basic Excel file, that includes all data by default and then, based on some params, we will remove data that should not be inside the Excel.
We don't use formulas at all (till now), so this will not be an issue for us. What we have, are merged cells (mostly as a header).
Removing a col afterwards is much simpler, else we would have to work with dozens of offset, based on the settings.

**Comment by gunnsth** [comment]
Thanks.  We are looking to implement it so the column can be removed and references can optionally be updated (best effort).

**Comment by gunnsth** [comment]
@polderudo Can you try https://github.com/unidoc/unioffice/pull/371 and see if it works for your case?  It is currently being reviewed and will be merged soon.
See
https://github.com/unidoc/unioffice/blob/0165c9928d1fde34201ac9cd391d5e417a22b63e/_examples/spreadsheet/remove-column/main.go
for an example

**Comment by gunnsth** [comment]
@polderudo This functionality is part of our newest release v1.3.0.  Closing.
