### ISSUE TITLE
How to save as Word Document

### ISSUE THREAD

**Issue by GZLHZ** [unidoc/unioffice#372]
## Description
Hello, could you please tell me how can I save the file as Word Document?

I run the code:
```
package main
import (
    "github.com/unidoc/unioffice/document"
)
func main() {
    doc, _ := document.Open("word.docx")
    doc.SaveToFile("newfile.docx")
}
```
## Expected Behavior
Expected file type is word document.

![QQ图片20200213214717](https://user-images.githubusercontent.com/45257277/74442485-891de280-4eac-11ea-8cd6-4284cd3f4c47.png)

## Actual Behavior
But the newfile type is Strict Open Xml Document
![QQ图片20200213214722](https://user-images.githubusercontent.com/45257277/74442486-89b67900-4eac-11ea-97f5-b07138499d34.png)

**Comment by zgordan-vv** [comment]
@GZLHZ can you tell your environment - OS, Office version? We cannot reproduce it so far

**Comment by GZLHZ** [comment]
> @GZLHZ can you tell your environment - OS, Office version? We cannot reproduce it so far

OK win10 & office2019

**Comment by zgordan-vv** [comment]
@GZLHZ Can you test a PR https://github.com/unidoc/unioffice/pull/399 with the code below:

```
package main

import (
    "github.com/unidoc/unioffice/document"
    st "github.com/unidoc/unioffice/schema/soo/ofc/sharedTypes"
)
func main() {
	doc, err := document.Open("document.docx")
	if err != nil {
		panic(err)
	}
	doc.SetConformance(st.ST_ConformanceClassTransitional)
	doc.SaveToFile("document_new.docx")

	/* another examples:
	doc.SetConformance(st.ST_ConformanceClassStrict) // this is for intentionally saving in strict mode
	doc.SaveToFile("document_new.docx")
	doc.SetConformance(st.ST_ConformanceClassUnset) // this is for removing conformance attribute at all, also leads to saving as Word document
	doc.SaveToFile("document_new.docx")*/
}
```

**Comment by GZLHZ** [comment]
@zgordan-vv  Hi, I tested the master code, and it save as word document.It works now.Thank you！！
