### ISSUE TITLE
[Question] Handling excel data

### ISSUE THREAD

**Issue by polderudo** [unidoc/unioffice#373]
As far as i saw, there is no way to get the data from an excel file as a matrix when running row by row.
unioffice removes empty cols in a row.

Is there any way to get the whole data of an excel, even with empty cols?

**Comment by zgordan-vv** [comment]
@polderudo Can you show what do you exactly do in order to reproduce?

**Comment by polderudo** [comment]
Lets say we have this file:

[test.xlsx](https://github.com/unidoc/unioffice/files/4297639/test.xlsx)

If you comment in the for loop, the second for loop will return different output
```
        s := ss.Sheets()[0]
	/*for _,row := range s.Rows(){
		fmt.Println("A:", row.Cell("A").GetString(), "B:", row.Cell("B").GetString(), "C:", row.Cell("C").GetString(), "D:", row.Cell("D").GetString())
	}*/

	for _,row := range s.Rows(){
		for _,cell := range row.Cells(){
			fmt.Println(cell.Reference(),":", cell.GetString())
		}
	}
```
It seems, like the cel "D2" which is empty, is generated only, when accessing it directly.

**Comment by zgordan-vv** [comment]
@polderudo creating all cells in the world seems unreasonable, so I am thinking about another method like row.CellsWithEmpty(lastCol string) which will create and return all cells including empty ones from column A to column lastColumn, will it be suitable?

**Comment by polderudo** [comment]
Creating all cells in the world seems unreasonable of course.
Passing in the lastCol, on the other hand is also not favorable. For us, e.g. we have a functionality ontop of the excel reading, which will fill an array of data based on the first line in an excel (header row). Thus the users can upload any excel files and the function will only read the cols that are defined in the apps. We don't even know the lastCol and they also append/remove colls sometimes (some external sources)

But don't we have the maxCol/maxRow in the library anyway? we should use that one. https://github.com/tealeg/xlsx also manages to do that.

**Comment by zgordan-vv** [comment]
Yes, thank you, we tend to make it with the last column used

**Comment by zgordan-vv** [comment]
Made a PR, example here https://github.com/unidoc/unioffice/pull/377/files#diff-82da1956b23d0c188eb79f727761301e

**Comment by polderudo** [comment]
@zgordan-vv this seems perfectly ok

**Comment by gunnsth** [comment]
@polderudo Can you check if the following example suits your use case:
https://github.com/unidoc/unioffice/blob/5e62adb061b3d8c656f9f2cb1da9bec2fe88fca3/_examples/spreadsheet/cells-with-empty/main.go

Basically we have a function that returns the maximum column with content in the sheet and then a function that can return all cells (including empty) including that column.

**Comment by polderudo** [comment]
@gunnsth That also works perfectly.

**Comment by gunnsth** [comment]
@polderudo Great, this has been merged into master, will be in next release.
