### ISSUE TITLE
Presentation: Problem injecting text/images into Powerpoint template placeholders

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unioffice#376]
## Description

An issue was raised via email:
> I am building an image export application and I would like to be able to take a PowerPoint template file and inject text and images into the template placeholders. I had no trouble injecting text into a template placeholder, but I have been unsuccessful in injecting images. Using the slide.AddImage method adds the image to a slide but not into a placeholder, and attempting to set common slide data on an existing pic placeholder has not worked for me. Could you send me a code snippet showing how I might do this?
>  I think the issue has to do with missing image relationships but I'm not sure how to correctly establish those.

## Expected Behavior
Expected template to be filled in with provided data and saved to an output PTTX file.

## Actual Behavior
Injecting text into placeholder works, but slide.AddImage method adds the image to a slide but not into a placeholder, and attempting to set common slide data on an existing pic placeholder has not worked for me.

A full example was provided to reproduce the issue.

**Comment by zgordan-vv** [comment]
Can we close it? Test case works on master now with _examples/presentation/use-template-with-image/main.go

**Comment by gunnsth** [comment]
Yes, the unioffice-examples link is:
https://github.com/unidoc/unioffice-examples/tree/master/presentation/use-template-with-image
Closing.
