### ISSUE TITLE
Can you support exporting Office as a picture

### ISSUE THREAD

**Issue by sohaha** [unidoc/unioffice#382]
There is a requirement to read the excel content and save it as a picture. 

Is there such an implementation at present?  

Thank you.

**Comment by gunnsth** [comment]
We have Word docx to PDF conversion https://github.com/unidoc/unioffice-examples/tree/master/document/doc-to-pdf
And UniPDF can render PDF to image https://github.com/unidoc/unipdf-examples/blob/master/render/pdf_image_render.go


This is not supported for XLSX/PPTX yet, but we will be adding that in the future.
