### ISSUE TITLE
Numbering.AddDefinition produces conflicting NumIdAttr's

### ISSUE THREAD

**Issue by freb** [unidoc/unioffice#383]
## Description

`AddDefinition` ([here](https://github.com/unidoc/unioffice/blob/dd7713e1e3f2b1324fc0263c2b967d70df56ead0/document/numbering.go#L106) has a but. It assumes that an `ID` of `1` greater than the highest numbered `AbstractNumberID` will work as a value for both a new `AbstractNumberID` and `num.NumIdAttr`. The problem is that frequently (including in default work documents), the NumIdAttr is 1 greater than the `AbstractNumberID`. So adding a numbering definition with this method will regularly produce `w:num` entries that have duplicate values for `NumIdAtt`.

## Expected Behavior

The values for both `AbstractNumId` and `NumIdAttr` on a numbering should be unique.

## Actual Behavior

Currently only the `AbstractNumberID` is checked for uniqueness.

You should make this:

```go
func (n Numbering) AddDefinition() NumberingDefinition {
	nx := wml.NewCT_Num()

	nextID := int64(1)
	for _, nd := range n.Definitions() {
		if nd.AbstractNumberID() >= nextID {
			nextID = nd.AbstractNumberID() + 1
		}
	}
	nx.NumIdAttr = nextID
	nx.AbstractNumId = wml.NewCT_DecimalNumber()
	nx.AbstractNumId.ValAttr = nextID

	an := wml.NewCT_AbstractNum()
	an.AbstractNumIdAttr = nextID

	n.x.AbstractNum = append(n.x.AbstractNum, an)
	n.x.Num = append(n.x.Num, nx)
	return NumberingDefinition{an}
}
```

Look like this:

```go
func (n Numbering) AddDefinition() NumberingDefinition {
	nx := wml.NewCT_Num()

	nextAbsNumId := int64(1)
	for _, nd := range d.Numbering.Definitions() {
		if nd.AbstractNumberID() >= nextAbsNumId {
			nextAbsNumId = nd.AbstractNumberID() + 1
		}
	}
	nextNumId := int64(1)
	for _, num := range d.Numbering.X().Num {
		if num.NumIdAttr >= nextNumId {
			nextNumId = nextNumId + 1
		}
	}

	nx.NumIdAttr = nextNumId
	nx.AbstractNumId = wml.NewCT_DecimalNumber()
	nx.AbstractNumId.ValAttr = nextAbsNumId

	an := wml.NewCT_AbstractNum()
	an.AbstractNumIdAttr = nextAbsNumId

	n.x.AbstractNum = append(n.x.AbstractNum, an)
	n.x.Num = append(n.x.Num, nx)
	return NumberingDefinition{an}
}
```

**Comment by gunnsth** [comment]
@freb PR #384 addresses this.

**Comment by freb** [comment]
The change looks good to me. Thanks!
