### ISSUE TITLE
InsertParagraphAfter does not properly handle table paragraphs

### ISSUE THREAD

**Issue by freb** [unidoc/unioffice#385]
## Description

`Document.InsertParagraphAfter` does not work as expected for paragraphs inside tables. The method description does not mention this.

## Expected Behavior

I expected the inserted paragraph appears within the same table cell, and just after the `relativeTo` paragraph. Another option is to update the documentation for `InsertParagraphAfter`.

## Actual Behavior

The inserted paragraph appears at the end of the document.

```go
package main

import (
	"github.com/unidoc/unioffice/color"
	"github.com/unidoc/unioffice/document"
	"github.com/unidoc/unioffice/measurement"
	"github.com/unidoc/unioffice/schema/soo/wml"
)

func main() {
	doc := document.New()

	paraBeforeTable := doc.AddParagraph()
	paraBeforeTable.AddRun().AddText("before table")

	table := doc.InsertTableAfter(paraBeforeTable)
	table.Properties().Borders().SetAll(wml.ST_BorderBasicBlackDots, color.AliceBlue, measurement.Point*2)
	tablePara1 := table.AddRow().AddCell().AddParagraph()
	tablePara1.AddRun().AddText("table paragraph 1")

	paraAfterTable := doc.AddParagraph()
	paraAfterTable.AddRun().AddText("after table")

	tablePara2 := doc.InsertParagraphAfter(tablePara1)
	tablePara2.AddRun().AddText("table paragraph 2") // inserted at end of document

	doc.SaveToFile("out.docx")
}
```

**Comment by gunnsth** [comment]
@freb Thanks for reporting.  PR #387 addresses this, can you confirm that it resolves the issue?

**Comment by freb** [comment]
That works great. Thanks!

**Comment by freb** [comment]
Sorry for the close and re-open. I just realized while checking the issue, `InsertTableAfer` has the same issue. Word/OOXML supports adding a table after a paragraph inside of a table cell, but `InsertTableAfter` places the new paragraph at the very end of the document currently.

I'm not sure if this is something you want to fix or just document as I'm sure the demand is much lower. I'm working on a Markdown to Docx renderer, and I think with an update to `InsertTableAfter`, rendering into a table cell would just work like it does rendering into the main body. But my use case is pretty specific.

**Comment by zgordan-vv** [comment]
@freb Can you try now the same PR? https://github.com/unidoc/unioffice/pull/387

**Comment by freb** [comment]
That looks great. Thanks!
