### ISSUE TITLE
how to get TextBox in presentation

### ISSUE THREAD

**Issue by tuoling805** [unidoc/unioffice#388]
## Description
I need to use GetTextBox function in Slides 
## Actual Behavior

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by tuoling805** [comment]
i fond the presentation Slide not have the GetTextBox function ,how to reset the page textbox content

**Comment by gunnsth** [comment]
Support for this has been added.  See the following for an example:
https://github.com/unidoc/unioffice-examples/blob/master/presentation/textbox/main.go
