### ISSUE TITLE
How to set doc pagesize and direction of page

### ISSUE THREAD

**Issue by Limaomi** [unidoc/unioffice#390]
## Actual Behavior

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by gunnsth** [comment]
@Limaomi Can you please fill out the bug report form fully.  Can you give an example of what you are trying to achieve?  What kind of page size and what direction?  Example files would be useful.

**Comment by gunnsth** [comment]
Example added in https://github.com/unidoc/unioffice/releases/tag/v1.12.0
https://github.com/unidoc/unioffice-examples/tree/master/document/page-size-and-orientation
