### ISSUE TITLE
build-examples.sh does not work on MacOS

### ISSUE THREAD

**Issue by securityguy** [unidoc/unioffice#403]
## Description
By default, the Go installer on MacOS installs at /usr/local/go and users can't modify the files. build-examples.sh uses the -i flag (which I do not believe is necessary with current Go releases) and also includes an extra '/'

## Expected Behavior
Samples build.

## Actual Behavior

go build runtime/cgo: copying /Users/eric/Library/Caches/go-build/8b/8be51c4acdf57f18c6f49a219549c18f398bcd08aebabd63c4283e62358db468-d: open /usr/local/go/pkg/darwin_amd64/runtime/cgo.a: permission denied
building _examples//spreadsheet/comments

go build runtime/cgo: copying /Users/eric/Library/Caches/go-build/8b/8be51c4acdf57f18c6f49a219549c18f398bcd08aebabd63c4283e62358db468-d: open /usr/local/go/pkg/darwin_amd64/runtime/cgo.a: permission denied

...

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

Removing the -i and the slash after _examples results in a clean build:

#!/bin/bash
go get -u github.com/go-ole/go-ole/oleutil
find _examples -maxdepth 2 -mindepth 2 -exec sh -c "cd {}; echo building {}; go build main.go" \;

**Comment by gunnsth** [comment]
This is probably no longer valid.  The examples are now in
https://github.com/unidoc/unioffice-examples
and build_examples.sh there is much simplified.
