### ISSUE TITLE
The temporary directory is not cleared

### ISSUE THREAD

**Issue by GarryGaller** [unidoc/unioffice#411]
Why does unioffice not delete temporary files in the TEMP folder after it?
There are still a huge number of gooxml-docx091614483 directories with files.
OS Windows.

**Comment by zgordan-vv** [comment]
This will be fixed in https://github.com/unidoc/unioffice/pull/423 , also the closing of the document is needed, say:

```
doc, err := document.Open("document.docx")
    if err != nil {
        log.Fatalf("error opening document: %s", err)
    }
    defer doc.Close() // <<<---
// etc
```
