### ISSUE TITLE
how to add a new form field to a word file 

### ISSUE THREAD

**Issue by BCCCA** [unidoc/unioffice#425]
## Description
in the examples  olny show to change the properties as "fill-out-form",  does this program have a function to add a formfield to a new docx file ? just like adding a CheckBox .
## Expected Behavior
create a check box field and add it to the existed docx file .
## Actual Behavior
can't find the API

Please include a reproducible code snippet or document attachment that

demonstrates the issue.

[form.docx](https://github.com/unidoc/unioffice/files/4937955/form.docx)
[add another form.docx](https://github.com/unidoc/unioffice/files/4937989/add.another.form.docx)

**Comment by gunnsth** [comment]
This is addressed in v1.6.0.  See also example
https://github.com/unidoc/unioffice-examples/blob/master/document/form-fields/main.go
