### ISSUE TITLE
Problem adding a dynamic image field in a mail merge

### ISSUE THREAD

**Issue by appiteasy** [unidoc/unioffice#429]
## Description
I am using mergeFields and I get the following error:
skipping unsupported element on CT_Picture {urn:schemas-microsoft-com:vml shapetype}
## Expected Behavior
My field "Picture" is not replaced in my word file, the content of Picture is a string like:
"http://localhost:8082/images/bsg1rnbb0co0sr4pm0qg"
This is the code in the word file for my 'Picture' field:
 {INCLUDEPICTURE "{MERGEFIELD Picture}" \d \* MERGEFORMAT}

Any idea why the field is not replaced?
If I am using the plane field without the INCLUDEPICTURE, it works like:
{MERGEFIELD Picture}
## Actual Behavior

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by zgordan-vv** [comment]
@appiteasy Hi! Can you attach your Word file or include exact steps how did you get this issue?

**Comment by gunnsth** [comment]
@appiteasy Please submit the minimal code and files needed to reproduce this issue so we can look into this.

**Comment by gunnsth** [comment]
Closing as we dont have a repro and longtime has elapsed. Please reopen with a repro if applicable.
