### ISSUE TITLE
How to insert nested tables

### ISSUE THREAD

**Issue by CR903** [unidoc/unioffice#430]
## Description

How to insert a table in a table paragraph, which can be anywhere. func InsertTableAfter doesn't seem to work.

Or how to add a table in Run?

**Comment by gunnsth** [comment]
@CR903 Please submit the minimal code and files needed to reproduce this issue so we can look into this.

**Comment by gunnsth** [comment]
This is addressed in v1.6.0, see also example
https://github.com/unidoc/unioffice-examples/blob/master/document/paragraphs_in_table/main.go
