### ISSUE TITLE
RangeReference.ParseRangeReference bug

### ISSUE THREAD

**Issue by m13934221960** [unidoc/unioffice#432]
## Description
when sheetname include char '!'（excel allowed），the following code will not work!
```golang
        sheetName := ""
	sp0 := strings.Split(s, "!")
	if len(sp0) == 2 {
		sheetName = sp0[0]
		s = sp0[1]
	}
```
## Expected Behavior
```golang
pos := strings.LastIndex(s, "!")
if pos < 0{
return CellReference{}, CellReference{}, errors.New("invalid range format")
}
sheetName := s[0:pos]
s = s[pos+1:]
```
## Actual Behavior

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by gunnsth** [comment]
This has been addressed in v1.6.0.  See also example code
https://github.com/unidoc/unioffice-examples/blob/master/spreadsheet/references-with-sheet-name/main.go
