### ISSUE TITLE
How to add a watermark to a Word document

### ISSUE THREAD

**Issue by 1321731966** [unidoc/unioffice#437]
Now I need to implement a function, I need to add watermark on word document, may I ask how I should do it?A: I've tried many ways but they don't work. Please tell me what I should do。

**Comment by gunnsth** [comment]
@1321731966 Please attach minimal code and files needed to reproduce the issue. For example some of the ways you have been attempting so far.

**Comment by 1321731966** [comment]
I am now trying to open a word document with a watermark and append subsequent content to it, but the watermark is gone!Here is my code
=================================================================================
doc,err:=document.Open("watermark.docx")
    if err!=nil{
        fmt.Println(err)
    }
    para:=doc.AddParagraph()
    run:=para.AddRun()
    run.AddText("Whatever, this is just test text")
    doc.SaveToFile("result.docx")


===================================================================================
Maybe there's a better way to put watermarks on word documents I don't know yet,

**Comment by gunnsth** [comment]
@1321731966 Can you please attach the file, watermark.docx so we can assess this properly?

**Comment by gunnsth** [comment]
We have added examples for the use case of adding watermarks:
- https://github.com/unidoc/unioffice-examples/tree/master/document/watermark-picture
- https://github.com/unidoc/unioffice-examples/tree/master/document/watermark-text
