### ISSUE TITLE
How to delete a table from document

### ISSUE THREAD

**Issue by Aled210** [unidoc/unioffice#451]
I process a word document where I need to replace some forms and eventually delete or hide tables based on condition.
At the moment I didn't find any way to achieve it.
What I tried is to manipulate the xml by unmarshalling it, here's how:

`
	buf := new(bytes.Buffer)
	buf.WriteString("")

	decoder := xml.NewDecoder(buf)

	err := doc.X().UnmarshalXML(decoder, xml.StartElement{})
	if err != nil {
		fmt.Println(err)
	}
`

The error I get is: 
`XML syntax error on line 1: unexpected EOF`

**Comment by sampila** [comment]
Hi @Aled210,

we added feature to remove node element for paragraph and table at https://github.com/unidoc/unioffice/releases/tag/v1.37.0, the usage example can be seen here https://github.com/unidoc/unioffice-examples/tree/master/document/node-remove.

We closing this issue for, feel free to re-open the issue if that still not resolve your issue.
