### ISSUE TITLE
Unable to save after manipulating a document with embedded image

### ISSUE THREAD

**Issue by Trimeego** [unidoc/unioffice#452]
## Description

I am trying to use unioffice to open an existing document with and embedded image in the header and perform a mail merge and save, however, the after performing the merge, I am unable to save the document with the following returned error.

`unsupported image source: {_cgd:<nil> _bgdf:{_bgfb:<nil>} _ebf:{Size:{X:0 Y:0} Format: Path: Data:<nil>} _agb: _eca:word/media/image2.}`

The document is viewable in Word.  Given the error above, it would seem that the image is getting embedded but is losing the file extension.

If I remove the image in the header, the document processes normally.

## Expected Behavior

I would expect the document to be able to load, as Word does.

## Actual Behavior

Using the attached file above:

----
	err := license.SetLicenseKey(licenseKey, customerName)
	if err != nil {
		panic(err)
	}

	doc, err := document.Open(filePath)
	if err != nil {
		panic(err)
	}

        doc.MailMerge(context) // context is a valid map[string]string

	err = doc.TemplateDocument.Save(writer)
        if err != nil {
		panic(err) // Error returned here.
	}

----

[US_Foods_Vendor_Agreement.docx](https://github.com/unidoc/unioffice/files/6812409/US_Foods_Vendor_Agreement.docx)

I am able to control the documents, so if there is a remediation that can be done in word, that would be fine.

**Comment by Trimeego** [comment]
Upon further investigation, the issue is limited to images _in the header_.  Using the same image as a source, when inserted in the _body_ of the document, no error is encountered when performing a mail merge.  With the same image inserted into the _header_, the error is encountered, even though Word clearly has the proper imageref.

**Comment by gunnsth** [comment]
This was fixed in release v1.14.0.
