### ISSUE TITLE
How can I get right NUMPAGES not in header or footer?

### ISSUE THREAD

**Issue by xswwhy** [unidoc/unioffice#459]
## Description
How can I get right NUMPAGES not in header or footer?
## Expected Behavior
get right NUMPAGES
## Actual Behavior
it's will done when I want to get `PAGE` and `NUMPAGES` in header or footer 
 ```
run.AddField(document.FieldCurrentPage)
run.AddField(document.FieldNumberOfPages)
```
but it's not work when I use the same code in the body of the word,it show me `1` whatever the code location

**Comment by gunnsth** [comment]
@xswwhy Please check example https://github.com/unidoc/unioffice-examples/blob/master/document/header-footer/main.go
