### ISSUE TITLE
How to replace a word in a paragraphs

### ISSUE THREAD

**Issue by moipa-cn** [unidoc/unioffice#465]
eg: I am a handsome man
i want replace man to women.
i try 
```
switch r.Text() {
case "man":
  r.ClearContent()
  r.AddText("I am a handsome women")
  r.AddBreak()
```
This is not what I want

I just need replace "women" in this paragraphs

**Comment by sampila** [comment]
Hi @moipa-cn,
You can do text replacement using the node feature.
Here's the example: [https://github.com/unidoc/unioffice-examples/blob/master/document/node-find-and-replace/main.go](https://github.com/unidoc/unioffice-examples/blob/master/document/node-find-and-replace/main.go)
