### ISSUE TITLE
Creating a table in a document cannot really merge cells

### ISSUE THREAD

**Issue by shenghui0779** [unidoc/unioffice#467]
## Description

```go
func main() {
	doc := document.New()
	defer doc.Close()

	{
		table := doc.AddTable()
		// width of the page
		table.Properties().SetWidthPercent(100)
		// with thick borers
		borders := table.Properties().Borders()
		borders.SetTop(wml.ST_BorderSingle, color.Auto, 2*measurement.Point)
		borders.SetRight(wml.ST_BorderSingle, color.Auto, 2*measurement.Point)
		borders.SetBottom(wml.ST_BorderSingle, color.Auto, 2*measurement.Point)
		borders.SetLeft(wml.ST_BorderSingle, color.Auto, 2*measurement.Point)

		row := table.AddRow()
		row.AddCell().AddParagraph().AddRun().AddText("Name")
		row.AddCell().AddParagraph().AddRun().AddText("John Smith")

		row = table.AddRow()
		cell := row.AddCell()
		cell.Properties().SetColumnSpan(2)
		cell.AddParagraph().AddRun().AddText("Street Address")
	}

	doc.SaveToFile("tables.docx")
}
```

## Expected Behavior

![image](https://user-images.githubusercontent.com/67535398/172088866-112acaf4-1977-4cae-b12d-003b6c4112e0.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/67535398/172088668-04001760-f29a-4ca6-a678-ef2442b14145.png)

![image](https://user-images.githubusercontent.com/67535398/172088736-7c0c7989-a544-46ff-b7cf-7a82593a8314.png)

![image](https://user-images.githubusercontent.com/67535398/172088757-18697821-b005-47d1-abd6-b7d68b7be64a.png)

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by sampila** [comment]
Hi @shenghui0779,
We checked the result of the code, it is having correct cell span when opened in MS Word 365.
As for information, we support the MS Word 2013 above.
![Screenshot 2022-06-06 082702](https://user-images.githubusercontent.com/15959715/172125769-9364bc95-facf-40a5-b579-8e1a8556c9d7.png)
[table-cell-span.docx](https://github.com/unidoc/unioffice/files/8842989/table-cell-span.docx)
