### ISSUE TITLE
Document append problem

### ISSUE THREAD

**Issue by shenghui0779** [unidoc/unioffice#468]
## Description

When I use `doc0.Append(doc1)`, the output file open fail

## Actual Behavior

![image](https://user-images.githubusercontent.com/67535398/172560204-1d0374a1-5ffd-4fb9-873c-fbd13cb3e845.png)

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by sampila** [comment]
Hi @shenghui0779,
Can you share more detail regarding the code and the files?
Is there any operation like adding more paragraphs or anything else before `doc0.Append(doc1)`?

**Comment by shenghui0779** [comment]
```go
func main() {
	doc0, err := document.Open("0.docx")

	if err != nil {
		log.Fatal(err)
	}

	defer doc0.Close()

	doc1, err := document.Open("1.docx")

	if err != nil {
		log.Fatal(err)
	}

	defer doc1.Close()

	if err = doc0.Append(doc1); err != nil {
		log.Fatal(err)
	}

	doc0.SaveToFile("output.docx")
}
```

[0.docx](https://github.com/unidoc/unioffice/files/8859484/0.docx)
[1.docx](https://github.com/unidoc/unioffice/files/8859486/1.docx)

**Comment by sampila** [comment]
Thank you, we will check this issue.

**Comment by sampila** [comment]
Hi @shenghui0779,

We released new UniOffice version https://github.com/unidoc/unioffice/releases/tag/v1.28.0 to solve this issue,

I closing this issue for now, let me know if you still having this after updating the UniOffice version.

Best regards,
Alip
