### ISSUE TITLE
Nil pointer when trying to extract image data

### ISSUE THREAD

**Issue by JNimkarLS** [unidoc/unioffice#470]
## Description
Hey folks. I am trying to extract raw image data from an MS word document. Here is the code snippet: 
```
        doc, err := document.Read(reader, reader.Size())
	if err != nil {
		return "", nil, fmt.Errorf("document read failure with error: %v", err)
	}
	defer doc.Close()

	for _, img := range doc.Images {
		if img.Data() == nil {
			ctx.Logger().Warn("received an image with nil data")
			continue
		}
		_, imgResults, err := ScanImage(ctx, clients, n, f, *img.Data())
		if err != nil {
			ctx.Logger().Errorf("image scanning failure with error: %v", err)
		}
	}
```
The doc.Images array is successfully populated with the number of images in the document however when I call img.Data() I receive a nil pointer.

## Expected Behavior
img.Data() should return a non-nil pointer

## Actual Behavior
img.Data() returns a nil pointer

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by sampila** [comment]
Hi @JNimkarLS,

Would you share the DOCX file that has the issue?

**Comment by sampila** [comment]
Hi @JNimkarLS,

To which email that you are sending the files? I checked my inbox and didn't see it

**Comment by JNimkarLS** [comment]
@sampila my apologies it got auto-blocked by our email service. I have resent it.

**Comment by JNimkarLS** [comment]
The email I sent it to: alipxsulistio@gmail.com

**Comment by JNimkarLS** [comment]
Great. Thank you!

**Comment by sampila** [comment]
Hi @JNimkarLS,

The img.Data() return `nil` because we load the from storage directly.
If you want to extract the image and print the image file bytes to CLI from the document, you can try this example.
```
// Copyright 2022 FoxyUtils ehf. All rights reserved.
package main

import (
	"io"
	"log"
	"os"
	"strconv"

	"github.com/unidoc/unioffice/common/license"
	"github.com/unidoc/unioffice/document"
)

func init() {
	// Make sure to load your metered License API key prior to using the library.
	// If you need a key, you can sign up and create a free one at https://cloud.unidoc.io
	err := license.SetMeteredKey(os.Getenv(`UNIDOC_LICENSE_API_KEY`))
	if err != nil {
		panic(err)
	}
}

func main() {
	doc, err := document.Open("document.docx")
	if err != nil {
		panic(err)
	}
	defer doc.Close()

	for i, img := range doc.Images {
		destImg := strconv.Itoa(i) + "." + img.Format()
		if err := extractImgFile(img.Path(), destImg); err != nil {
			panic(err)
		}

		// Incase you want to read the bytes file.
		imgBytes, err := os.ReadFile(img.Path())
		if err != nil {
			panic(err)
		}

		log.Printf("bytes: %v\n", imgBytes)
	}
}

func extractImgFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)

	return err
}

```

Hope this help.

Best regards,
Alip

**Comment by JNimkarLS** [comment]
Thank you for the response @sampila . To make a long story short, I do not have access to the file directly. I am given the file as raw content (byte array). How can I extract the image data from this raw content?

**Comment by sampila** [comment]
The library read the image and stores it in the temporary directory.
It depends on how the image was added to the document, if the image byte array is `nil`, you can get the image by using `img.Path()`

**Comment by JNimkarLS** [comment]
@sampila your solution fixed the problem. Thank you so much. Instead of using img.Data() I used os.ReadFile(img.Path()) to extract the raw bytes.

**Comment by sampila** [comment]
@JNimkarLS glad to hear that and thanks for the information.
We closing this issue.
