### ISSUE TITLE
docx to pdf

### ISSUE THREAD

**Issue by pingyuan7** [unidoc/unioffice#472]
## Description

When converting docx to PDF, the format is simply wrong.
Fonts, especially when there is Chinese, will not be converted at all.

## Actual Behavior

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by sampila** [comment]
Hi @pingyuan7
Could you share the `DOCX` file and code with us?

Best regards,
Alip

**Comment by pingyuan7** [comment]
func main() {

	doc, err := document.Open("test.docx")
	if err != nil {
		log.Fatalf("error opening document: %s", err)
	}
	defer doc.Close()
	c := convert.ConvertToPdf(doc)

	err = c.WriteToFile("test.pdf")
	if err != nil {
		log.Fatalf("error converting document: %s", err)
	}
[test.docx](https://github.com/unidoc/unioffice/files/9238775/test.docx)


[test.pdf](https://github.com/unidoc/unioffice/files/9238776/test.pdf)
}

**Comment by sampila** [comment]
Hi @pingyuan7,

Thank you for the code and files, we are looking into this and will inform you as soon as possible.

**Comment by sampila** [comment]
We released new version with improvements of font name lookup, you can try to use new UniOffice version [v1.21.0](https://github.com/unidoc/unioffice/releases/tag/v1.21.0)

Let us know if you still have issue regarding this.
