### ISSUE TITLE
How to know a textline belongs to which page in a docx file

### ISSUE THREAD

**Issue by hoangthanh283** [unidoc/unioffice#478]
## Description
Is there any way to know a text line belongs to which page in a .docx file?

## Expected Behavior
We should have an attribute in a text Item to get the page information:
```
for ei, e := range extracted.Items {
      text: = e.Text`
      page_index = e.PageIndex
```

## Actual Behavior
There is only `Text`, `DrawingInfo`, `Paragraph`, `Hyperlink`, `TableInfo` BUT no `PageInfo` in the `TextItem`.

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by anovik** [comment]
This is not possible for docx format and there is no reliable way to do that. Docx (OOXML) doesn't contain any page numbers related to paragraphs, lines, etc. In MS Word, page numbers for items are defined only during rendering.
