### ISSUE TITLE
Could not extract information (text, table, image, ...etc) from a .doc file

### ISSUE THREAD

**Issue by hoangthanh283** [unidoc/unioffice#479]
## Description
* I tried the [text-extraction example](https://github.com/unidoc/unioffice-examples/tree/master/document/text_extraction) with a .doc file that is converted from the [document.docx](https://github.com/unidoc/unioffice-examples/blob/master/document/text_extraction/document.docx) (I attached my input document below), but I couldn't get any information from the file.

## Expected Behavior
* Can we get the text and other information like parsing a .docx file?
* We should have something like this:
0
Text: Paragraph 1
Bold: false
Italic: false
........
FLATTENED:
Paragraph 1
Paragraph 2
Table 1
Column 1
Column 2
Row 1
Cell 1-1
Cell 1-2
Paragraph 3
Paragraph 4
Hi, I am a Text Box

## Actual Behavior
* Get nothing.

## Input document:
* [document.doc.zip](https://github.com/unidoc/unioffice/files/9915264/document.doc.zip)

**Comment by sampila** [comment]
Hi @hoangthanh283,

We only support the DOCX file for Microsoft Word file.
