### ISSUE TITLE
License error text is confusing

### ISSUE THREAD

**Issue by Gordy96** [unidoc/unioffice#480]
## Description
When given a wrong customer name on license bootstrap error message has expected and actual values switched places which causes more confusion during debug
## Expected Behavior
Error message to say `customer name mismatch, expected 'EXPECTED', but got 'ACTUAL'`
## Actual Behavior
Error message to say `customer name mismatch, expected 'ACTUAL', but got 'EXPECTED'`

You need switch `customerName` and `_daba .CustomerName` places near `"L\u0069ce\u006es\u0065 \u0063\u006f\u0064\u0065\u0020i\u0073\u0073\u0075e\u0020\u002d\u0020\u0043\u0075s\u0074\u006f\u006de\u0072\u0020\u006e\u0061\u006d\u0065\u0020\u006d\u0069\u0073\u006da\u0074\u0063\u0068, e\u0078\u0070\u0065\u0063\u0074\u0065d\u0020\u0027\u0025\u0073\u0027\u002c\u0020\u0062\u0075\u0074\u0020\u0067o\u0074 \u0027\u0025\u0073\u0027"`

**Comment by sampila** [comment]
Hi @Gordy96,

Could you tell us the detail about what operations that you are trying to do or share the code snippet with us?
Here's the example for loading licenses: 
- Offline license [https://github.com/unidoc/unioffice-examples/blob/master/license/offline/main.go](https://github.com/unidoc/unioffice-examples/blob/master/license/offline/main.go)
- Metered license [https://github.com/unidoc/unioffice-examples/blob/master/license/metered/main.go](https://github.com/unidoc/unioffice-examples/blob/master/license/metered/main.go)

Best regards,
Ali

**Comment by Gordy96** [comment]
Hi @sampila, the offline one, I believe
```go
err := license.SetLicenseKey(key, customerName)
if err != nil {
	return nil, err
}
```
I had an error that said `customer name mismatch, expected 'blahblah\n', but got 'blahblah'`
Then I thought maybe something wrong on the actual key and added `\n` to it and error became `customer name mismatch, expected 'blahblah\n\n', but got 'blahblah'`. Which concludes that there already was extra `\n` in the first place and error message misled me. After I removed extra `\n` from my `customerName` error disappeared

**Comment by sampila** [comment]
Hi @Gordy96 thank you for reporting this.
We will do fix on that error message.

As for now, are you able to load the license and use UniOffice?

**Comment by Gordy96** [comment]
Yes all's good now

**Comment by sampila** [comment]
Thank you for the confirmation.
We closing this issue now.
