### ISSUE TITLE
Is this still Open Source software?

### ISSUE THREAD

**Issue by probonopd** [unidoc/unioffice#482]
Is this still Open Source software?

If not, why is it on GitHub?

**Comment by prochac** [comment]
Then why do you bother to publish this here? It feels more like an ad. Collecting GitHub starts, and then pull the rug.

**Comment by probonopd** [comment]
Looks like UniPDF was dual-licensed with AGPL/commercial license until 2020. So for open source development, you'd need to fork from an older version.
