### ISSUE TITLE
Runtime error extracting text from Word document

### ISSUE THREAD

**Issue by JulieCraig** [unidoc/unioffice#489]
## Description
Trying to extract text from a word document gets a runtime error

## Expected Behavior
Using code from https://github.com/unidoc/unioffice-examples/blob/master/document/text_extraction/main.go (but just get the flattened text and not the individual formatted items). I attempted to extract the text from a word document. The line "extracted := doc.ExtractText()" produces an error.

## Actual Behavior
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17dfcf6]

goroutine 1 [running]:
github.com/unidoc/unioffice/document.(*Document).ExtractText(0xc000002300)

Please include a reproducible code snippet or document attachment that
demonstrates the issue.
As an example, this document gets the error
https://create.microsoft.com/en-us/template/bold-attorney-resume-d62d84e1-905a-45d1-b1ae-624b8cae6381

**Comment by sampila** [comment]
Hi @JulieCraig,

Thanks for reporting this issue, we will checks this issue and inform the updates to you.

**Comment by sampila** [comment]
Hi @JulieCraig,

We released new UniOffice version https://github.com/unidoc/unioffice/releases/tag/v1.25.0 to solve this issue.
