### ISSUE TITLE
No text in document after converting a Word document to PDF

### ISSUE THREAD

**Issue by JulieCraig** [unidoc/unioffice#491]
## Description
Trying to convert a Word document to PDF gives a mostly blank PDF.

## Expected Behavior
Using code from https://github.com/unidoc/unioffice-examples/blob/master/document/convert_to_pdf/main.go, I attempted to convert a document to PDF. A PDF resembling the Word document should be produced.

## Actual Behavior
A document is produced but it mostly blank - no text but sometimes characters like slashes. Extracting text from the same Word document does produce text.

Please include a reproducible code snippet or document attachment that
demonstrates the issue.
As an example, this document gets the error
https://create.microsoft.com/en-us/template/bold-attorney-resume-d62d84e1-905a-45d1-b1ae-624b8cae6381

**Comment by joinimran** [comment]
Hi @JulieCraig - We are investigating this issue and will update you soon.

**Comment by joinimran** [comment]
Hi @JulieCraig - We have found the issue and our development team is looking for the options for implementations. As soon as I will have further updates regarding ETA etc, I will let you know. 
Thanks

**Comment by sampila** [comment]
We released new UniOffice version https://github.com/unidoc/unioffice/releases/tag/v1.26.0

**Comment by anovik** [comment]
@JulieCraig Your issue is fixed in the latest versions of UniOffice. We have just released https://github.com/unidoc/unioffice/releases/tag/v1.38.0
