### ISSUE TITLE
How to split a run and/or paragraph while preserving styling

### ISSUE THREAD

**Issue by lavens** [unidoc/unioffice#492]
## Description
In the example below, I would like to replace the text `{{table_content}}` with a table, and split the run that contains the text into two new runs whilst preserving any styling (lines break, font style, etc) that was applied to the original run. Any suggestions on how this can be done? Thanks!

## Example Template Document
_Depending on the laws in your state, the person who writes a real estate sales contract can be the buyer or the seller.
The first step of the legal process of buying or selling a home involves creating a real estate purchase agreement.
The purchase agreement {{table_content}} outlines the terms of the sale but does not transfer the property itself — more steps come afterward to finalize a legal property transfer._

## Expected Behavior
_Depending on the laws in your state, the person who writes a real estate sales contract can be the buyer or the seller.
The first step of the legal process of buying or selling a home involves creating a real estate purchase agreement.
The purchase agreement_
| Header | Header | Header | Header |
|--------|--------|--------|--------|
| Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | 

_outlines the terms of the sale but does not transfer the property itself — more steps come afterward to finalize a legal property transfer._

**Comment by joinimran** [comment]
Hi @lavens - Thank you for reporting this issue. Our development team is looking into this. We are expecting the fix as soon as possible and will share the details via internal support channel. 

Thanks.
Imran.

**Comment by sampila** [comment]
Hi @lavens,

Starting from version https://github.com/unidoc/unioffice/releases/tag/v1.26.0, we added the function for "SetProperties" where it can be used to preserving the run styles.

Best regards, 
Alip
