### ISSUE TITLE
No text extracted from PowerPoint file

### ISSUE THREAD

**Issue by JulieCraig** [unidoc/unioffice#493]
## Description
Trying to convert extract text from a Microsoft presentation yields empty results.

## Expected Behavior
Using code from https://github.com/unidoc/unioffice-examples/blob/master/presentation/text_extraction/main.go, text should be extracted from a pptx file.

## Actual Behavior
No text is extracted.

Please include a reproducible code snippet or document attachment that
demonstrates the issue.
As an example, this document does not produce any text:
https://create.microsoft.com/en-us/template/frosted-design-3a8dded6-d092-4621-8b57-26753d9617ca

**Comment by joinimran** [comment]
Hi @JulieCraig - Thank you for contacting the UniDoc support team. We are looking into this issue and will update you soon.
Thanks
