### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by robermar23** [unidoc/unioffice#502]
## Description
Do you offer a path for developers to unit test application logic without counting against a metered license or does that require a perpetual license?

## Expected Behavior
Some way to test the application without having a real license key

## Actual Behavior
Exception raised when no key provided and metered key use is incremented any time the package is loaded into memory the first time, regardless of cause.

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by sampila** [comment]
Hi @robermar23,

Normally the metered license will be start counted as usages and when it being used.

Could you share a runnable code snippet so we can reproduce the issue in our end?

Thanks

**Comment by ipod4g** [comment]
@robermar23 The metered license key should be used for all testing activities to ensure consistency and accurate results.

If you have any questions or need assistance with the license key, feel free to reach out.

Thanks
