### ISSUE TITLE
Chinese characters, a null pointer error will occur.

### ISSUE THREAD

**Issue by leptobo** [unidoc/unioffice#515]
## Description
func Open (filename string )(*Document ,error ){_gegb ,_efgb :=_ed .Open (filename );if _efgb !=nil {return nil ,_be .Errorf ("e\u0072r\u006f\u0072\u0020\u006f\u0070\u0065\u006e\u0069n\u0067\u0020\u0025\u0073: \u0025\u0073",filename ,_efgb );};defer _gegb .Close ();
_faec ,_efgb :=_ed .Stat (filename );if _efgb !=nil {return nil ,_be .Errorf ("e\u0072r\u006f\u0072\u0020\u006f\u0070\u0065\u006e\u0069n\u0067\u0020\u0025\u0073: \u0025\u0073",filename ,_efgb );};_ =_faec ;return Read (_gegb ,_faec .Size ());};

When using this method, if the file path (filename) contains Chinese characters, a null pointer error will occur.
## 实际行为
func Open (filename string )(*Document ,error ){_gegb ,_efgb :=_ed .Open (filename );if _efgb !=nil {return nil ,_be .Errorf ("e\u0072r\u006f\u0072\u0020\u006f\u0070\u0065\u006e\u0069n\u0067\u0020\u0025\u0073: \u0025\u0073",filename ,_efgb );};defer _gegb .Close ();
_faec ,_efgb :=_ed .Stat (filename );if _efgb !=nil {return nil ,_be .Errorf ("e\u0072r\u006f\u0072\u0020\u006f\u0070\u0065\u006e\u0069n\u0067\u0020\u0025\u0073: \u0025\u0073",filename ,_efgb );};_ =_faec ;return Read (_gegb ,_faec .Size ());};

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by sampila** [comment]
Hi @leptobo could you share the DOCX file?

**Comment by leptobo** [comment]
> Hi @leptobo could you share the DOCX file?
i need your email

**Comment by sampila** [comment]
> > Hi @leptobo could you share the DOCX file?
> > i need your email

You can send the file to support@unidoc.io, with the information linked to this issue.

**Comment by leptobo** [comment]
> > > Hi @leptobo could you share the DOCX file?
> > > i need your email
> 
> You can send the file to [support@unidoc.io](mailto:support@unidoc.io), with the information linked to this issue.

I have already sent the email. Later, I tried different Chinese files; smaller files could be opened correctly, but larger ones reported a null pointer error. Reading the file from the email resulted in an error.

**Comment by sampila** [comment]
> > > > Hi @leptobo could you share the DOCX file?
> > > > i need your email
> > 
> > 
> > You can send the file to [support@unidoc.io](mailto:support@unidoc.io), with the information linked to this issue.
> 
> I have already sent the email. Later, I tried different Chinese files; smaller files could be opened correctly, but larger ones reported a null pointer error. Reading the file from the email resulted in an error.

Thanks, we will checks that and inform you the updates later.
