### ISSUE TITLE
docx remove table

### ISSUE THREAD

**Issue by zekoliu** [unidoc/unioffice#522]
May I ask how to delete the form in the word document? Could you please provide the deleted api document

**Comment by sampila** [comment]
Hi @zekoliu,

Currently the remove function only available for some document elements, like paragraph and run elements, however we are planning to extends it to support other elements also like table.

**Comment by sampila** [comment]
Hi @zekoliu,

we added feature to remove node element for paragraph and table at https://github.com/unidoc/unioffice/releases/tag/v1.37.0, the usage example can be seen here https://github.com/unidoc/unioffice-examples/tree/master/document/node-remove.

We closing this issue for, feel free to re-open the issue if that still not resolve your issue.

**Comment by sampila** [comment]
https://github.com/unidoc/unioffice/issues/451

**Comment by zekoliu** [comment]
thinks



发自我的iPhone


------------------ Original ------------------
From: Alip Sulistio ***@***.***&gt;
Date: Thu,Oct 24,2024 10:32 PM
To: unidoc/unioffice ***@***.***&gt;
Cc: liu huanze ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [unidoc/unioffice] docx remove table (Issue #522)





 
Hi @zekoliu,
 
we added feature to remove node element for paragraph and table at https://github.com/unidoc/unioffice/releases/tag/v1.37.0, the usage example can be seen here https://github.com/unidoc/unioffice-examples/tree/master/document/node-remove.
 
We closing this issue for, feel free to re-open the issue if that still not resolve your issue.
